[project]
name = "fastapi-flyio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.4",
    "uvicorn[standard]>=0.39.0",
]
